# By default we use a mock local endpoint instead of connecting to Woopra:
online_analytics_woopra_enabled: false
online_analytics_local_endpoint_enabled: true
online_analytics_log_level: debug

osoan_cluster_name: devenv

osoan_log_level: debug
osoan_git_repo: "https://github.com/dgoodwin/online-analytics.git"
osoan_git_ref: "logging-revamp"
